# default configuration
eureka:
 client:
   serviceUrl:
     defaultZone: http://localhost:8761/eureka/

activityproducer:
  bootstrap-server: localhost:9092
  topic:
    circle: circle
    mailbox: mailbox
    user: user
    recommendation: recommendation
  
---

# production configuration
spring:
    profiles: production
  
eureka:
 client:
   serviceUrl:
     defaultZone: http://172.23.238.189:8761/eureka/

activityproducer:
  bootstrap-server: 172.23.238.219:9092, 172.23.238.219:9093, 172.23.238.219:9094
  topic:
    circle: circle
    mailbox: mailbox
    user: user
    recommendation: recommendation
