# default configuration
eureka:
 client:
   serviceUrl:
     defaultZone: http://localhost:8761/eureka/

activityproducer:
  bootstrap-server: 172.23.239.202:9092, 172.23.239.176:9092, 172.23.239.182:9092
  topic:
    circle: circle
    mailbox: mailbox
    user: user
    recommendation: recommendation
  
---

# production configuration
spring:
    profiles: production
  
eureka:
 client:
   serviceUrl:
     defaultZone: http://172.23.239.182:8761/eureka/

activityproducer:
  bootstrap-server: 172.23.239.202:9092, 172.23.239.176:9092, 172.23.239.182:9092
  topic:
    circle: circle
    mailbox: mailbox
    user: user
    recommendation: recommendation