# default configuration
eureka:
 client:
   serviceUrl:
     defaultZone: http://localhost:8761/eureka/
     
spring:
 data:
  mongodb:
    username: superAdmin
    password: admin123
    authentication-database: admin
    database: gupshup
    
circleservice:
   bootstrap-server: localhost:9092
   topic:
    circle: circle
    mailbox: mailbox
    user: user
    recommendation: recommendation

---

# production configuration
spring:
    profiles: production
    
eureka:
 client:
   serviceUrl:
     defaultZone: http://172.23.239.182:8761/eureka/
     
spring:
 data:
  mongodb:
    username: superAdmin
    password: admin123
    authentication-database: admin
    database: gupshup

circleservice:
   bootstrap-server: localhost:9092
   topic:
    circle: circle
    mailbox: mailbox
    user: user
    recommendation: recommendation
