# default configuration
server:
  port: 8080
  
eureka:
 client:
   serviceUrl:
     defaultZone: http://172.23.238.204:8761/eureka/

security:
  oauth2:
    resource:
      userInfoUri: http://172.23.239.202:9000/me
   

---

# production configuration
spring:
    profiles: production
    
server:
  port: 8080
  
eureka:
 client:
   serviceUrl:
     defaultZone: http://172.23.238.189:8761/eureka/
     
security:
  oauth2:
    resource:
      userInfoUri: http://172.23.238.186:9000/me

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 50000

ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 50000
