# default configuration
server:
  port: 8080
  
eureka:
 client:
   serviceUrl:
     defaultZone: http://localhost:8761/eureka/

security:
  oauth2:
    resource:
      userInfoUri: http://localhost:9000/me
   
---

# production configuration
spring:
    profiles: production
    
server:
  port: 8080
  
eureka:
 client:
   serviceUrl:
     defaultZone: http://172.23.239.182:8761/eureka/
     
security:
  oauth2:
    resource:
      userInfoUri: http://172.23.239.202:9000/me