# default configuration
server:
  port: 8081
  
eureka:
 client:
   serviceUrl:
     defaultZone: http://localhost:8761/eureka/
   
---

# production configuration
spring:
    profiles: production
    
server:
  port: 8080
  
eureka:
 client:
   serviceUrl:
     defaultZone: http://172.23.239.182:8761/eureka/