# default configuration
eureka:
 client:
   serviceUrl:
     defaultZone: http://172.23.239.173:8761/eureka/
     
spring:
  profiles: native
  data:
    neo4j:
      uri: http://172.23.239.173:7474
      username: neo4j
      password: pass
       
---

# production configuration
spring:
 profiles: production
 data:
    neo4j:
      uri: http://172.23.239.173:7474
      username: neo4j
      password: pass
    
eureka:
 client:
   serviceUrl:
     defaultZone: http://172.23.239.182:8761/eureka/
     
  
       
