# default configuration
eureka:
 client:
   serviceUrl:
     defaultZone: http://172.23.239.182:8761/eureka/
     
spring:
  data:
    mongodb:
      username: superAdmin
      password: admin123
      authentication-database: admin
      database: gupshup  
      port: 27017
      
<<<<<<< HEAD
logging:
  level:
    org:
      springframework:
        web: INFO

    com:
      stackroute:
        gupshup:
          userservice: DEBUG
          
  file: logs/spring-boot-logging.log
=======
userproducer:
  bootstrap-servers: 172.23.239.202:9092
  mailbox-topic: mailbox
  recommendation-topic: recommendation
  
  
userconsumer:
  bootstrap-servers: 172.23.239.202:9092
  consumer-groupid: test-consumer-group
  clientid: simple
  user-topic: user
>>>>>>> 5a0a0455d3c4a2c72901561988a71b12257b539b
     
---

# production configuration
spring:
    profiles: production
    
eureka:
 client:
   serviceUrl:
     defaultZone: http://172.23.239.182:8761/eureka/
     
spring:
  data:
    mongodb:
      username: superAdmin
      password: admin123
      authentication-database: admin
      database: gupshup  
      port: 27017
     
userproducer:
  bootstrap-servers: 172.23.239.202:9092
  mailbox-topic: mailbox
  recommendation-topic: recommendation
  
  
userconsumer:
  bootstrap-servers: 172.23.239.202:9092
  consumer-groupid: test-consumer-group
  clientid: simple
  user-topic: user

     
