# default configuration
eureka:
 client:
   serviceUrl:
     defaultZone: http://localhost:8761/eureka/
     
spring:
  data:
    mongodb:
      username: superAdmin
      password: admin123
      authentication-database: admin
      database: gupshup  
      

logging:
  level:
    org:
      springframework:
        web: INFO

    com:
      stackroute:
        gupshup:
          userservice: DEBUG
          
  file: logs/spring-boot-logging.log

userservice:
    bootstrap-servers: localhost:9092
    groupId: user
    topic:
      user: user 
      mailbox: mailbox
      recommendation: recommendation
     
---

# production configuration
spring:
    profiles: production
    
    data:
    mongodb:
      username: superAdmin
      password: admin123
      authentication-database: admin
      database: gupshup  
      port: 27017
    
eureka:
 client:
   serviceUrl:
     defaultZone: http://172.23.239.160:8761/eureka/
      
logging:
  level:
    org:
      springframework:
        web: INFO

    com:
      stackroute:
        gupshup:
          userservice: DEBUG
          
  file: logs/spring-boot-logging.log

     
userservice:
    bootstrap-servers: 172.23.239.202:9092, 172.23.239.176:9092, 172.23.239.182:9092
    groupId: user
    topic:
      user: user 
      mailbox: mailbox
      recommendation: recommendation
      
authserver:
  url: http://172.23.239.202:9000/register

